### ISSUE TITLE
Wrong localizations directory included

### ISSUE THREAD

**Issue by Flo354** [webjars/parsleyjs#4]
Hi,

There is an error in the pom.xml

```
<move todir="${destDir}/i18n" flatten="true">
  <fileset dir="${project.build.directory}/Parsley.js-${upstream.version}">
    <include name="src/i18n/*.js" />
  </fileset>
</move>
```

You are including localizations from "src" folder instead of "dist" folder.
The problem is that localizations from src folder contain a line which make unusable localization

> import Parsley from '../parsley';

Example : 
https://github.com/guillaumepotier/Parsley.js/blob/master/dist/i18n/fr.js
https://github.com/guillaumepotier/Parsley.js/blob/master/src/i18n/fr.js

Could you fix the issue?

Thanks,

**Comment by jamesward** [comment]
Should I just include the whole `dist` dir and leave everything else out?  Or include both `dist` and `src` as subdirs?

**Comment by Flo354** [comment]
I think that you have to include the whole `dist` directory and that's all
